# Generated by Django 5.1.2 on 2024-11-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
