# Generated by Django 5.1.2 on 2024-11-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cartitem_size_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
